const btn_1 = document.querySelector('#btn_1')
const btn_2 = document.querySelector('#btn_2')
const btn_3 = document.querySelector('#btn_3')
const btn_4 = document.querySelector('#btn_4')
const btn_5 = document.querySelector('#btn_5')
const btn_6 = document.querySelector('#btn_6')
const btn_7 = document.querySelector('#btn_7')
const btn_8 = document.querySelector('#btn_8')
const btn_9 = document.querySelector('#btn_9')

btn_1.addEventListener( 'click', () => btn_1.style.backgroundColor = 'maroon')
btn_2.addEventListener( 'click', () => btn_2.style.backgroundColor = 'orangered')
btn_3.addEventListener( 'click', () => btn_3.style.backgroundColor = 'yellowgreen')
btn_4.addEventListener( 'click', () => btn_4.style.backgroundColor = 'greenyellow')
btn_5.addEventListener( 'click', () => btn_5.style.backgroundColor = 'aqua')
btn_6.addEventListener( 'click', () => btn_6.style.backgroundColor = 'darkblue')
btn_7.addEventListener( 'click', () => btn_7.style.backgroundColor = 'blueviolet')
btn_8.addEventListener( 'click', () => btn_8.style.backgroundColor = 'grey')
btn_9.addEventListener( 'click', () => btn_9.style.backgroundColor = 'pink')

